# Header
menu:
  Home: /
  Meetup: https://meetup.com/London-Clojurians
  Calendar: https://www.meetup.com/London-Clojurians/events/
  Coding Dojos: /coding-dojos/
  Skillscasts: https://skillsmatter.com/explore?content=skillscasts&location=&q=clojure
  Mailing List: http://groups.google.com/group/london-clojurians
  Jobs List: https://groups.google.com/forum/#!forum/london-clojurian-jobs
  Code of Conduct: /code-of-conduct/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
# - category
# - tag
# - tagcloud
# - archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter: ldnclj
google_plus:
fb_admins:
fb_app_id:
